Repository BIT-Studio-OP/CraftMyPortfolio, pull requests merged in 2023-08, with the labels that each got.

#47 created contact form
  .gitignore
  example.env
  package-lock.json
  package.json
  src/App.jsx
  src/components/content/HomeContent.jsx
  src/components/header/Header.jsx
  src/components/home/Home.jsx
  src/pages/Contact.jsx
  src/pages/Home.jsx
Labels: 4

#48 Functionality user details to firebase
  firestore.rules
  src/App.jsx
  src/components/detailsForm/detailsForm.jsx
  src/components/header/Header.jsx
Labels: 4

#64 feat: updating the stlying of the details form and allowing the user …
  src/components/details/details.jsx
  src/components/header/Header.jsx
Labels: 4

#66 feat auto fill user info details #56 #65 #52
  src/App.jsx
  src/components/details/details.jsx
  src/components/footer/Footer.jsx
  src/components/getDetails/getDetails.jsx
  src/components/header/Header.jsx
  src/components/templates/Templates.jsx
  src/components/templates/footers/templateFooterOne.jsx
Labels: 1, 2, 4, 8, Dani-op

#75 feat functionality for details form info to firebase
  src/components/content/DetailsContent.jsx
Labels: 4, 8, Dani-op
