Repository BIT-Studio-OP/CraftMyPortfolio, pull requests merged in 2023-06, with the labels that each got.

#23 Jake footer
  .firebaserc
  firebase.json
  firestore.indexes.json
  firestore.rules
  package-lock.json
  package.json
  src/App.jsx
  src/components/content/Body.jsx
  src/components/footer/Footer.jsx
  src/components/header/Header.jsx
  src/index.css
  src/utils/Firestore.jsx
Labels: enhancement, 2, base-site

#25 Navbar
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/header/Header.jsx
  src/components/header/nav.css
  src/index.css
  src/main.jsx
Labels: enhancement, 4, base-site

#22 Dani op #3 4 16 sign in,sign up,logout forms
  .firebase/hosting.ZGlzdA.cache
  package-lock.json
  package.json
  src/App.jsx
  src/components/auth/SignIn.jsx
  src/components/auth/SignOut.jsx
  src/components/auth/SignUp.jsx
  src/components/content/Body.jsx
  src/index.css
  src/main.jsx
  src/utils/Firestore.jsx
  src/utils/Spinner.jsx
  src/utils/context/AuthContext.jsx
Labels: Dani-op

#24 Dani op #19 landing page
  src/App.jsx
  src/components/home/Home.jsx
  tailwind.config.js
Labels: 8, Dani-op
